version: ~> 1.0

env:
  global:
    - secure: "BrDoqAjZeFnW5vGe3AtVSHgXWb16DthqQwiefN+lNhcllQw6WXFx4PvpwNGM1PI3voLg6YJM/9mOrVOk5nSYjh65DQmlJ6jNX1ezJoI30hURhykoXJNrKr25JTF54GhgMgk/KiR3fhGQYJgpXUxPxYPBt3PvXd7uY0cMIYCFAW8gwrupVfHbPo1zGbxHzxysBlxpQQAclBj4pVMIX5chkVM/Yviv72mEkyoKPJpQgCCn7CstQSLhHtM+EK+bHpqjIk37cnGi/lTZYxlmrMjEeU/UXxL2/y2uA43W8sdsD2vCEiMcexjD2cqhjOr1Qn1zZgzHchSapkHsju1KHdCOeiWE/yV9Ni/fteb4doKnSQOIY/hqofqkyETFfNarOa9Zsm5i03QUyFNub2hr6k6lWRal5MaOErGiUAVlKCYj5KBe/AYHC758rmm1YIukYXKn2cBfApt+sCSc50WGEqjiT1iiUBD6dCP1p4Skd6RpLbwIL6f9THvzAqpQRJpZAtOmffIKpQ0+RUjEQF9UlwPKOgpdAOw2XrK0asrgfh9goiiB7QrzJ0GPa0Wy7BTfi3ksNXskdnatGAFAJiRPBkmcshRFrLx4UIlLx5pTW88G2T0yYXNGi+mEQHXY9rcozZJlVIESYSL1NgRV5aW/gfYC4hqmFfB+93MFG5g05HJ/dlA="

    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="docs-requirements.txt dev-requirements.txt requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="pcdsdaq"

    # The name of the conda package
    - CONDA_PACKAGE="pcdsdaq"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt. E.g. PyQt
    - CONDA_EXTRAS="pip"
    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS=""

#jobs:
#  allow_failures:
#    - name: "Python - PIP"

import:
  # This import enables a set of standard python jobs including:
  # - Build
  #   - Anaconda Package Build
  # - Tests
  #   - Python Linter
  #   - Package Linter
  #   - Documentation
  #   - Python 3.6 - PIP based
  #   - Python 3.6, 3.7 & 3.8 - Conda base
  # - Deploy
  #   - Documentation using doctr
  #   - Conda Package - uploaded to pcds-dev and pcds-tag
  #   - PyPI
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
