{% set package_name = "pcdsdaq" %}
{% set import_name = "pcdsdaq" %}
{% set version = load_file_regex(load_file=os.path.join(import_name, "_version.py"), regex_pattern=".*version = '(\S+)'").group(1) %}

package:
  name: {{ package_name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv



requirements:
  build:
  - python >=3.6
  - setuptools_scm
  - pip
  run:
  - python >=3.6
  - ophyd >=1.5.0
  - bluesky >=1.6.0
  - toolz



test:
  imports:
  - pcdsdaq



about:
  home: https://github.com/pcdshub/pcdsdaq
  license: SLAC Open License
  summary: DAQ Control Interface
