{% set data = load_setup_py_data() %}

package:
  name: pcdsdaq
  version : {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - bluesky >=1.6.0
    - ophyd >=1.5.0
    - psdaq-control-minimal >=3.3.19
    - toolz

test:
  imports:
    - pcdsdaq

about:
  home: https://github.com/pcdshub/pcdsdaq
  license: SLAC Open License
  summary: DAQ Control Interface
